"""Small, separately loaded city-map recipes from the accepted saved world."""

from collections.abc import Mapping
import hashlib
import json
from pathlib import Path
import re

from .model import WorldGrid
from .city_site import city_site_context
from .city_transport import CityCorridor, CityTransportIndex
from .cartographic_rivers import river_width_field
from .presentation import derive_presentation_assets
from .society.model import SocietyLayers
from .society.onomastics import lineage_entity_candidates


CITY_MAP_SCHEMA = "world-atlas-city-map-v1"


def write_city_map_assets(
    output: str | Path,
    grid: WorldGrid,
    society: SocietyLayers,
    settlement_locations: Mapping[str, tuple[float, float]],
    *,
    terrain_field,
    harbors: Mapping,
    physical_paths,
) -> None:
    """Export one data-only JSON file per city, retaining its displayed anchor.

    The same grid, population, era, water mask and transport corridors that
    determine the atlas supply these recipes. City geometry is generated by
    the client only when that city is opened.
    """
    for city in society.settlements:
        anchor=settlement_locations.get(city.identifier)
        if anchor and (not city.row<=anchor[0]<city.row+1 or not city.column<=anchor[1]<city.column+1):
            if not harbors.get(city.identifier) or terrain_field.sample_points(anchor[1],anchor[0])<=0:
                raise ValueError('a displayed anchor outside its native land cell needs a dry, verified harbor site')
    assets = derive_presentation_assets(
        grid, society, settlement_locations=settlement_locations,
    )
    if any(not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]*", recipe.identifier)
           for recipe in assets.city_recipes):
        raise ValueError("city map identifiers must be safe standalone filenames")
    destination = Path(output) / "city-maps"
    destination.mkdir(parents=True, exist_ok=True)
    height, width = grid.shape
    transport = CityTransportIndex(society.transport, width, corridors=(
        CityCorridor(f"corridor-{index:05d}", mode, tuple(map(tuple, points)))
        for index, (mode, importance, points) in enumerate(physical_paths)))
    governments = {form.identifier: form.key for form in society.politics.government_forms}
    state_government = {entity.country_identifier: governments[entity.government_form_identifier]
                        for entity in society.politics.political_entities}
    capitals={state.core_settlement_id for state in society.politics.states}
    states={state.identifier:state.name for state in society.politics.states}
    holy={r.holy_settlement_id:r for r in society.religions.religions}
    languages={language.identifier:language.name_family for language in society.cultures.languages}
    river_widths=river_width_field(grid)
    for recipe in assets.city_recipes:
        document = recipe.document()
        document["culture"]["government"] = state_government.get(recipe.state_identifier)
        document['culture']['isCapital']=recipe.identifier in capitals
        document['culture']['stateName']=states.get(recipe.state_identifier)
        religion=holy.get(recipe.identifier)
        document['culture']['holyReligion']=({'name':religion.name,'tradition':religion.tradition} if religion else None)
        document['harbor'] = harbors.get(recipe.identifier)
        context = city_site_context(grid, document, terrain_field, river_widths=river_widths)
        name_seed=int.from_bytes(hashlib.sha256(recipe.identifier.encode('utf-8')).digest()[:4],'big')
        context['nameRoots']=list(lineage_entity_candidates(languages[recipe.language_identifier], 'landscape', seed=name_seed)[:40])
        bounds = context["bounds"]
        context['namedFeatures']=[{'id':f.identifier,'name':f.name,'kind':f.feature_type,
            'location':{'row':f.row+.5,'column':f.column+.5}}
            for f in society.geographic_features
            if bounds['north']<=f.row+.5<=bounds['south']
            and bounds['west']<=f.column+.5<=bounds['east']]
        document["transport"]["corridors"] = [corridor.document() for corridor in transport.corridors(
            (bounds["north"], bounds["west"], bounds["south"], bounds["east"]))]
        if document['harbor']:
            document['transport']['corridors'].append({'id':recipe.identifier+'-harbor-access',
                'kind':'road','points':document['harbor']['access']})
        payload = {
            "schema": CITY_MAP_SCHEMA,
            "gridDigest": assets.grid_digest,
            "grid": {"width": width, "height": height},
            "recipe": document,
            "siteContext": context,
        }
        (destination / f"{recipe.identifier}.json").write_text(
            json.dumps(payload, ensure_ascii=False, separators=(",", ":"), allow_nan=False) + "\n",
            encoding="utf-8",
        )
