"""Illustrative latitude/elevation perennial snowline for Eirenor.

This module deliberately models a relative snowline, not metres above sea
level.  It is intended for the authored relative-elevation atlas and therefore
returns an explainable threshold raster that can be reviewed or replaced by a
future climate model.  Ocean cells are always excluded from the snow surface.

The default threshold is symmetric about the equator and follows

``clamp(pole + (equator - pole) * cos(abs(latitude)) ** exponent)``.
At and beyond the explicit ``polar_full_snow_latitude`` cap, the baseline
threshold is zero so even near-sea-level relative land can be perennial snow.

The only optional adjustment is an explicit deterministic snowline offset.  No
random noise or hidden climate state is used.
"""

from __future__ import annotations

import math
from collections import deque
from dataclasses import dataclass
from typing import Sequence

import numpy as np

from world_atlas.physical.planetary_grid import (
    PlanetConfig,
    coriolis_parameter,
    daily_mean_insolation_at_solar_longitude,
)


SNOWLINE_MODEL_NAME = "illustrative/perennial relative snowline"
HYDROCLIMATE_MODEL_NAME = "seasonal-insolation-wind-orographic-shadow-runoff-v3"
SEASON_IDS = ("vernal", "june", "autumnal", "december")
SEASON_SOLAR_LONGITUDES = (0.0, 90.0, 180.0, 270.0)


@dataclass(frozen=True, slots=True)
class SnowlineConfig:
    """Parameters for the illustrative/perennial relative snowline.

    ``equator_threshold`` and ``pole_threshold`` are relative-elevation values
    in ``[0, 1]``.  The defaults intentionally mean that equatorial lowlands
    remain snow-free while only the highest relative elevations are snowy near
    latitude zero; at 75 degrees, low/mid relative elevations can qualify; and
    the polar threshold approaches near-sea-level relative elevation.

    ``max_offset`` bounds an optional explicit ``snowline_offset``.  A positive
    offset raises the threshold (warmer/drier illustration), while a negative
    offset lowers it (cooler/moister illustration).  Offsets are never sampled
    or generated by this module.

    ``polar_full_snow_latitude`` is an illustrative latitude cap, not a claim
    about a physical climate boundary.  At or beyond it, the unadjusted
    threshold is exactly zero on land.
    """

    equator_threshold: float = 0.90
    pole_threshold: float = 0.02
    exponent: float = 1.10
    max_offset: float = 0.15
    polar_full_snow_latitude: float = 68.0


@dataclass(frozen=True, slots=True)
class SnowlineResult:
    """Deterministic snowline arrays and the metadata needed to explain them."""

    perennial_snow_mask: np.ndarray
    snow_threshold: np.ndarray
    latitude: np.ndarray
    relative_elevation: np.ndarray
    land_mask: np.ndarray
    snowline_offset: np.ndarray
    model_name: str


@dataclass(frozen=True, slots=True)
class MonsoonHydroclimateResult:
    """Four-season relative climate fields and their annual hydrologic summary."""

    seasonal_precipitation: np.ndarray
    seasonal_wind_east: np.ndarray
    seasonal_wind_north: np.ndarray
    seasonal_runoff_yield: np.ndarray

    annual_precipitation: np.ndarray
    dry_season_runoff: np.ndarray
    monsoon_index: np.ndarray
    perennial_runoff_yield: np.ndarray
    distance_to_ocean: np.ndarray
    model_name: str


class SnowlineError(ValueError):
    """Raised when snowline inputs or configuration are invalid."""


def _validate_config(config: SnowlineConfig) -> None:
    if not isinstance(config, SnowlineConfig):
        raise SnowlineError("config must be a SnowlineConfig instance")
    try:
        equator_threshold = float(config.equator_threshold)
        pole_threshold = float(config.pole_threshold)
        exponent = float(config.exponent)
        max_offset = float(config.max_offset)
        polar_full_snow_latitude = float(config.polar_full_snow_latitude)
    except (TypeError, ValueError) as error:
        raise SnowlineError("snowline configuration values must be numeric") from error
    values = (
        ("equator_threshold", equator_threshold),
        ("pole_threshold", pole_threshold),
        ("exponent", exponent),
        ("max_offset", max_offset),
        ("polar_full_snow_latitude", polar_full_snow_latitude),
    )
    for name, value in values:
        try:
            finite = math.isfinite(value)
        except (TypeError, ValueError) as error:
            raise SnowlineError(f"{name} must be a finite number") from error
        if not finite:
            raise SnowlineError(f"{name} must be a finite number")
    if not 0.0 <= pole_threshold <= 1.0:
        raise SnowlineError("pole_threshold must be between zero and one")
    if not 0.0 <= equator_threshold <= 1.0:
        raise SnowlineError("equator_threshold must be between zero and one")
    if pole_threshold > equator_threshold:
        raise SnowlineError("pole_threshold cannot exceed equator_threshold")
    if exponent <= 0.0:
        raise SnowlineError("exponent must be positive")
    if max_offset < 0.0:
        raise SnowlineError("max_offset cannot be negative")
    if not 0.0 < polar_full_snow_latitude <= 90.0:
        raise SnowlineError("polar_full_snow_latitude must be in (0, 90]")


def _as_relative_elevation(
    value: np.ndarray | Sequence[Sequence[float]],
) -> np.ndarray:
    try:
        elevation = np.asarray(value, dtype=np.float64)
    except (TypeError, ValueError) as error:
        raise SnowlineError("relative_elevation must be a numeric 2-D array") from error
    if elevation.ndim != 2 or elevation.size == 0:
        raise SnowlineError("relative_elevation must be a non-empty 2-D array")
    return elevation.copy()


def _as_land_mask(
    value: np.ndarray | Sequence[Sequence[bool]],
    shape: tuple[int, int],
) -> np.ndarray:
    try:
        mask = np.asarray(value)
    except (TypeError, ValueError) as error:
        raise SnowlineError("land_mask must be a 2-D array") from error
    if mask.ndim != 2 or mask.shape != shape:
        raise SnowlineError(f"land_mask must have shape {shape}")
    return mask.astype(bool, copy=True)


def _as_latitude(
    value: np.ndarray | Sequence[float] | Sequence[Sequence[float]],
    shape: tuple[int, int],
) -> np.ndarray:
    try:
        raw = np.asarray(value, dtype=np.float64)
    except (TypeError, ValueError) as error:
        raise SnowlineError("latitude must be a numeric row or cell array") from error
    height, _ = shape
    if raw.ndim == 1 and raw.shape == (height,):
        latitude = np.broadcast_to(raw[:, None], shape).copy()
    elif raw.ndim == 2 and raw.shape == shape:
        latitude = raw.copy()
    else:
        raise SnowlineError(
            f"latitude must have one value per row ({height},) or per cell {shape}"
        )
    if not np.all(np.isfinite(latitude)):
        raise SnowlineError("latitude contains non-finite values")
    if np.any(latitude < -90.0) or np.any(latitude > 90.0):
        raise SnowlineError("latitude must be within the EIR-GEOG-1 range [-90, 90]")
    return latitude


def _as_offset(
    value: float | np.ndarray | Sequence[float] | Sequence[Sequence[float]] | None,
    shape: tuple[int, int],
    maximum: float,
) -> np.ndarray:
    if value is None:
        return np.zeros(shape, dtype=np.float64)
    try:
        raw = np.asarray(value, dtype=np.float64)
    except (TypeError, ValueError) as error:
        raise SnowlineError("snowline_offset must be numeric") from error
    if raw.ndim == 1 and raw.shape == (shape[0],):
        raw = raw[:, None]
    try:
        offset = np.broadcast_to(raw, shape).astype(np.float64, copy=True)
    except ValueError as error:
        raise SnowlineError(f"snowline_offset cannot broadcast to shape {shape}") from error
    if not np.all(np.isfinite(offset)):
        raise SnowlineError("snowline_offset contains non-finite values")
    tolerance = max(1.0e-12, maximum * 1.0e-12)
    if np.any(np.abs(offset) > maximum + tolerance):
        raise SnowlineError(f"snowline_offset must stay within +/-{maximum}")
    return offset


def _distance_to_ocean(land: np.ndarray, ocean: np.ndarray) -> np.ndarray:
    """Return four-neighbour inland distance with longitude wrapping."""

    height, width = land.shape
    distance = np.full(land.shape, height + width, dtype=np.int32)
    coastal = np.zeros(land.shape, dtype=bool)
    coastal[1:, :] |= land[1:, :] & ocean[:-1, :]
    coastal[:-1, :] |= land[:-1, :] & ocean[1:, :]
    coastal |= land & np.roll(ocean, 1, axis=1)
    coastal |= land & np.roll(ocean, -1, axis=1)
    queue: deque[tuple[int, int]] = deque()
    for row, column in np.argwhere(coastal):
        cell = (int(row), int(column))
        distance[cell] = 1
        queue.append(cell)
    while queue:
        row, column = queue.popleft()
        next_distance = int(distance[row, column]) + 1
        for next_row, next_column in (
            (row - 1, column),
            (row + 1, column),
            (row, (column - 1) % width),
            (row, (column + 1) % width),
        ):
            if not 0 <= next_row < height or not land[next_row, next_column]:
                continue
            if next_distance >= distance[next_row, next_column]:
                continue
            distance[next_row, next_column] = next_distance
            queue.append((next_row, next_column))
    distance[~land] = 0
    return distance


def _smooth_wrapped_longitude(field: np.ndarray, passes: int) -> np.ndarray:
    """Diffuse a cell field without wrapping across either pole."""

    result = np.asarray(field, dtype=np.float64).copy()
    for _ in range(passes):
        north = np.empty_like(result)
        south = np.empty_like(result)
        north[0] = result[0]
        north[1:] = result[:-1]
        south[-1] = result[-1]
        south[:-1] = result[1:]
        result = (
            4.0 * result
            + north
            + south
            + np.roll(result, 1, axis=1)
            + np.roll(result, -1, axis=1)
        ) / 8.0
    return result


def _gradient_wrapped_longitude(field: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return north-south and periodic east-west cell gradients."""

    value = np.asarray(field, dtype=np.float64)
    gradient_y = np.gradient(value, axis=0)
    gradient_x = (np.roll(value, -1, axis=1) - np.roll(value, 1, axis=1)) * 0.5
    return gradient_y, gradient_x


def _normalised_vector(
    east: np.ndarray,
    north: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    speed = np.hypot(east, north)
    unit_east = np.divide(
        east, speed, out=np.zeros_like(east), where=speed > 1.0e-12
    )
    unit_north = np.divide(
        north, speed, out=np.zeros_like(north), where=speed > 1.0e-12
    )
    return unit_east, unit_north, speed


def _freeze_climate_array(value: np.ndarray, dtype: np.dtype = np.dtype("float64")) -> np.ndarray:
    contiguous = np.ascontiguousarray(value, dtype=dtype)
    return np.frombuffer(contiguous.tobytes(), dtype=contiguous.dtype).reshape(
        contiguous.shape
    )


def compute_monsoon_hydroclimate(
    relative_elevation: np.ndarray | Sequence[Sequence[float]],
    land_mask: np.ndarray | Sequence[Sequence[bool]],
    ocean_mask: np.ndarray | Sequence[Sequence[bool]],
    latitude: np.ndarray | Sequence[float] | Sequence[Sequence[float]],
    *,
    planet: PlanetConfig,
) -> MonsoonHydroclimateResult:
    """Resolve four relative seasonal wind, rain and runoff states.

    The model is deliberately causal but non-metric: exact seasonal
    insolation drives land/ocean thermal contrast; large-scale latitude belts
    and the configured Coriolis sign turn the pressure flow; ocean fetch and
    inland decay carry moisture; local upslope flow produces windward rain and
    leeward drying.  Every annual hydrology field is derived from these four
    snapshots, never from a separately painted monsoon mask.
    """

    elevation = _as_relative_elevation(relative_elevation)
    land = _as_land_mask(land_mask, elevation.shape)
    ocean = _as_land_mask(ocean_mask, elevation.shape)
    if np.any(land & ocean):
        raise SnowlineError("land_mask and ocean_mask must be disjoint")
    if not isinstance(planet, PlanetConfig):
        raise SnowlineError("planet must be a PlanetConfig instance")
    latitude_grid = _as_latitude(latitude, elevation.shape)
    land_elevation = elevation[land]
    if not np.all(np.isfinite(land_elevation)):
        raise SnowlineError("relative_elevation contains non-finite land values")
    if np.any(land_elevation < 0.0) or np.any(land_elevation > 1.0):
        raise SnowlineError("relative_elevation land values must be within [0, 1]")
    distance = _distance_to_ocean(land, ocean)
    short_side = float(max(1, min(elevation.shape)))
    inland_distance = distance.astype(np.float64)
    coastal_moisture = np.exp(-inland_distance / max(2.0, short_side * 0.22))
    absolute_latitude = np.abs(latitude_grid)
    distance_y, distance_x = _gradient_wrapped_longitude(inland_distance)
    inland_east, inland_north, _ = _normalised_vector(distance_x, -distance_y)
    elevation_y, elevation_x = _gradient_wrapped_longitude(
        np.where(land, elevation, 0.0)
    )
    relief = np.hypot(elevation_x, elevation_y)
    relief_scale = float(np.quantile(relief[land], 0.90)) if np.any(land) else 1.0
    relief_scale = max(relief_scale, 1.0e-6)
    land_thermal_mass = _smooth_wrapped_longitude(land.astype(np.float64), 6)
    longitude_scale = max(1.0, elevation.shape[1] / 360.0)
    latitude_scale = max(1.0, elevation.shape[0] / 180.0)
    coriolis = np.asarray(coriolis_parameter(latitude_grid, planet), dtype=np.float64)
    coriolis_scale = max(float(np.max(np.abs(coriolis))), 1.0e-12)
    coriolis_relative = coriolis / coriolis_scale

    seasonal_precipitation = np.empty((4, *elevation.shape), dtype=np.float64)
    seasonal_wind_east = np.empty_like(seasonal_precipitation)
    seasonal_wind_north = np.empty_like(seasonal_precipitation)
    seasonal_runoff = np.empty_like(seasonal_precipitation)
    row_indices = np.arange(elevation.shape[0], dtype=np.int32)[:, None]
    column_indices = np.arange(elevation.shape[1], dtype=np.int32)[None, :]
    season_insolation = np.stack(
        [
            np.asarray(
                daily_mean_insolation_at_solar_longitude(
                    latitude_grid,
                    solar_longitude,
                    planet,
                ),
                dtype=np.float64,
            )
            for solar_longitude in SEASON_SOLAR_LONGITUDES
        ]
    )
    annual_insolation = np.mean(season_insolation, axis=0)
    tilt_scale = min(1.5, planet.axial_tilt_degrees / 23.44)

    for season_index, solar_longitude in enumerate(SEASON_SOLAR_LONGITUDES):
        seasonal_angle = math.radians(solar_longitude)
        declination = math.degrees(
            math.asin(
                math.sin(math.radians(planet.axial_tilt_degrees))
                * math.sin(seasonal_angle)
            )
        )
        insolation = season_insolation[season_index]
        insolation_anomaly = (insolation - annual_insolation) / max(
            planet.solar_constant_wm2, 1.0
        )
        thermal_response = np.where(
            land,
            1.0,
            1.0 / planet.ocean_heat_capacity_factor,
        )
        thermal = (
            insolation / max(planet.solar_constant_wm2, 1.0)
            + insolation_anomaly * thermal_response * (0.65 + 0.70 * land_thermal_mass)
            - 0.20 * elevation
        )
        thermal = _smooth_wrapped_longitude(thermal, 3)
        thermal_y, thermal_x = _gradient_wrapped_longitude(thermal)
        pressure_east = thermal_x / longitude_scale
        pressure_north = -thermal_y / latitude_scale

        trade_easterly = np.exp(-((absolute_latitude / 24.0) ** 2))
        midlatitude_westerly = np.exp(-(((absolute_latitude - 48.0) / 18.0) ** 2))
        polar_easterly = np.exp(-(((absolute_latitude - 77.0) / 12.0) ** 2))
        zonal = -0.52 * trade_easterly + 0.42 * midlatitude_westerly - 0.20 * polar_easterly
        meridional = np.tanh((declination - latitude_grid) / 22.0)
        meridional *= np.exp(-((latitude_grid - declination) / 54.0) ** 2)

        base_east = planet.rotation_sign * zonal + 3.2 * pressure_east
        base_north = 0.62 * meridional + 3.2 * pressure_north
        deflection = 0.65 * coriolis_relative
        wind_east = base_east + deflection * base_north
        wind_north = base_north - deflection * base_east
        unit_east, unit_north, raw_speed = _normalised_vector(wind_east, wind_north)
        speed_scale = max(float(np.quantile(raw_speed, 0.95)), 1.0e-9)
        relative_speed = np.clip(raw_speed / speed_scale, 0.0, 1.0)
        wind_east = unit_east * relative_speed
        wind_north = unit_north * relative_speed

        onshore = np.clip(
            wind_east * inland_east + wind_north * inland_north,
            -1.0,
            1.0,
        )
        upslope = np.clip(
            (wind_east * elevation_x - wind_north * elevation_y) / relief_scale,
            -1.0,
            1.0,
        )
        itcz_rain = np.exp(-(((latitude_grid - declination) / 18.0) ** 2))
        storm_track = np.exp(-(((absolute_latitude - 50.0) / 17.0) ** 2))
        subtropical_dry = np.exp(-(((absolute_latitude - 29.0) / 10.0) ** 2))
        hemisphere_summer = np.sin(np.deg2rad(latitude_grid)) * math.sin(
            seasonal_angle
        )
        summer_rain = np.clip(hemisphere_summer, 0.0, 1.0) * tilt_scale
        maritime_supply = coastal_moisture * np.clip(0.48 + 0.52 * onshore, 0.08, 1.0)
        windward = np.clip(upslope, 0.0, 1.0) * maritime_supply
        leeward = np.clip(-upslope, 0.0, 1.0) * (0.35 + 0.65 * coastal_moisture)
        flow_row = np.where(wind_north > 0.12, -1, np.where(wind_north < -0.12, 1, 0))
        flow_column = np.where(wind_east > 0.12, 1, np.where(wind_east < -0.12, -1, 0))
        upstream_rows = np.clip(
            row_indices - flow_row, 0, elevation.shape[0] - 1
        )
        upstream_columns = (column_indices - flow_column) % elevation.shape[1]
        shadow_source = np.where(land, np.clip(upslope, 0.0, 1.0), 0.0)
        orographic_shadow = np.zeros_like(shadow_source)
        for _ in range(18):
            shadow_source = np.where(
                land,
                shadow_source[upstream_rows, upstream_columns] * 0.96,
                0.0,
            )
            orographic_shadow = np.maximum(orographic_shadow, shadow_source)
        precipitation = np.clip(
            0.07
            + 0.38 * itcz_rain
            + 0.28 * storm_track
            - 0.22 * subtropical_dry
            + 0.34 * maritime_supply
            + 0.30 * summer_rain * (0.25 + 0.75 * coastal_moisture)
            + 0.34 * windward
            - 0.26 * leeward
            - 1.25 * orographic_shadow * (0.35 + 0.65 * coastal_moisture),
            0.02,
            1.35,
        )
        runoff = precipitation * np.clip(
            0.28 + 0.42 * coastal_moisture + 0.30 * elevation,
            0.18,
            1.0,
        )
        precipitation[~land] = 0.0
        runoff[~land] = 0.0
        seasonal_precipitation[season_index] = precipitation
        seasonal_wind_east[season_index] = wind_east
        seasonal_wind_north[season_index] = wind_north
        seasonal_runoff[season_index] = runoff

    annual_precipitation = np.mean(seasonal_precipitation, axis=0)
    dry_season_runoff = np.min(seasonal_runoff, axis=0)
    perennial_runoff = 0.20 * np.mean(seasonal_runoff, axis=0) + 0.80 * dry_season_runoff
    precipitation_range = np.ptp(seasonal_precipitation, axis=0)
    wind_reversal = np.maximum(
        0.0,
        -(
            seasonal_wind_east[1] * seasonal_wind_east[3]
            + seasonal_wind_north[1] * seasonal_wind_north[3]
        ),
    )
    onset = 1.0 - np.exp(-inland_distance / max(1.0, short_side * 0.025))
    penetration = np.exp(-inland_distance / max(4.0, short_side * 1.20))
    monsoon_latitude = np.exp(-(((absolute_latitude - 22.0) / 20.0) ** 2))
    monsoon_index = np.clip(
        tilt_scale
        * monsoon_latitude
        * onset
        * penetration
        * (
            0.62
            * np.clip(
                precipitation_range / np.maximum(annual_precipitation, 0.05),
                0.0,
                1.0,
            )
            + 0.38 * np.clip(wind_reversal, 0.0, 1.0)
        ),
        0.0,
        1.0,
    )
    for field in (
        annual_precipitation,
        dry_season_runoff,
        monsoon_index,
        perennial_runoff,
    ):
        field[~land] = 0.0

    return MonsoonHydroclimateResult(
        seasonal_precipitation=_freeze_climate_array(seasonal_precipitation),
        seasonal_wind_east=_freeze_climate_array(seasonal_wind_east),
        seasonal_wind_north=_freeze_climate_array(seasonal_wind_north),
        seasonal_runoff_yield=_freeze_climate_array(seasonal_runoff),
        annual_precipitation=_freeze_climate_array(annual_precipitation),
        dry_season_runoff=_freeze_climate_array(dry_season_runoff),
        monsoon_index=_freeze_climate_array(monsoon_index),
        perennial_runoff_yield=_freeze_climate_array(perennial_runoff),
        distance_to_ocean=_freeze_climate_array(distance, np.dtype("int32")),
        model_name=HYDROCLIMATE_MODEL_NAME,
    )


def compute_perennial_snowline(
    relative_elevation: np.ndarray | Sequence[Sequence[float]],
    land_mask: np.ndarray | Sequence[Sequence[bool]],
    latitude: np.ndarray | Sequence[float] | Sequence[Sequence[float]],
    snowline_offset: float
    | np.ndarray
    | Sequence[float]
    | Sequence[Sequence[float]]
    | None = None,
    config: SnowlineConfig | None = None,
) -> SnowlineResult:
    """Compute a deterministic illustrative perennial relative snowline.

    ``latitude`` accepts either one EIR-GEOG-1 latitude per raster row or a
    full per-cell array.  ``relative_elevation`` values are required to be
    finite and within ``[0, 1]`` only where ``land_mask`` is true; ocean values
    are ignored and may be ``NaN``.  The returned ``snow_threshold`` is still a
    finite explanatory raster for every valid latitude cell, while
    ``perennial_snow_mask`` is strictly zero on ocean cells.

    The base threshold is

    ``clamp(pole_threshold + (equator_threshold - pole_threshold) *
    cos(abs(latitude)) ** exponent, 0, 1)`` away from the polar cap, and zero
    at or beyond ``polar_full_snow_latitude``.

    A supplied offset is broadcast over the raster and added before the final
    clamp.  Positive values raise the illustrative snowline; negative values
    lower it.  No metre-scale or physical temperature precision is implied.

    The vectorized computation is ``O(N)`` time and memory for ``N`` cells.
    """

    active_config = config or SnowlineConfig()
    _validate_config(active_config)
    equator_threshold = float(active_config.equator_threshold)
    pole_threshold = float(active_config.pole_threshold)
    exponent = float(active_config.exponent)
    max_offset = float(active_config.max_offset)
    polar_full_snow_latitude = float(active_config.polar_full_snow_latitude)
    elevation = _as_relative_elevation(relative_elevation)
    land = _as_land_mask(land_mask, elevation.shape)
    latitude_grid = _as_latitude(latitude, elevation.shape)
    offset = _as_offset(snowline_offset, elevation.shape, max_offset)

    land_elevation = elevation[land]
    if not np.all(np.isfinite(land_elevation)):
        raise SnowlineError("relative_elevation contains non-finite land values")
    if np.any(land_elevation < 0.0) or np.any(land_elevation > 1.0):
        raise SnowlineError("relative_elevation land values must be within [0, 1]")

    absolute_latitude = np.abs(latitude_grid)
    radians = np.deg2rad(absolute_latitude)
    cosine = np.cos(radians)
    # Make the exact pole endpoint exact instead of exposing a tiny floating
    # point cosine residue in the explanatory raster.
    cosine = np.where(absolute_latitude >= 90.0, 0.0, np.clip(cosine, 0.0, 1.0))
    base_threshold = pole_threshold + (
        equator_threshold - pole_threshold
    ) * np.power(cosine, exponent)
    # The illustrative model has a deliberately explicit polar cap: at and
    # above this latitude the baseline threshold is zero, so low relative
    # elevation can qualify without pretending to know a metre-scale climate.
    # An explicit caller-supplied offset still adjusts that baseline.
    # Growing seasons shorten before the permanent polar cap begins.  Lower
    # the local snowline through that transition so subpolar coasts do not
    # remain visually temperate until one abrupt final latitude band.
    subpolar_start = max(48.0, polar_full_snow_latitude - 18.0)
    polar_transition = np.clip(
        (absolute_latitude - subpolar_start)
        / max(polar_full_snow_latitude - subpolar_start, 1.0),
        0.0,
        1.0,
    )
    base_threshold *= 1.0 - 0.82 * np.power(polar_transition, 1.25)
    base_threshold = np.where(
        absolute_latitude >= polar_full_snow_latitude,
        0.0,
        base_threshold,
    )
    threshold = np.clip(base_threshold + offset, 0.0, 1.0)
    perennial_snow = land & (elevation >= threshold)

    return SnowlineResult(
        perennial_snow_mask=perennial_snow,
        snow_threshold=threshold,
        latitude=latitude_grid,
        relative_elevation=elevation,
        land_mask=land,
        snowline_offset=offset,
        model_name=SNOWLINE_MODEL_NAME,
    )


def compute_snowline(
    relative_elevation: np.ndarray | Sequence[Sequence[float]],
    land_mask: np.ndarray | Sequence[Sequence[bool]],
    latitude: np.ndarray | Sequence[float] | Sequence[Sequence[float]],
    snowline_offset: float
    | np.ndarray
    | Sequence[float]
    | Sequence[Sequence[float]]
    | None = None,
    config: SnowlineConfig | None = None,
) -> SnowlineResult:
    """Readable alias for :func:`compute_perennial_snowline`."""

    return compute_perennial_snowline(
        relative_elevation,
        land_mask,
        latitude,
        snowline_offset=snowline_offset,
        config=config,
    )


__all__ = [
    "HYDROCLIMATE_MODEL_NAME",
    "SNOWLINE_MODEL_NAME",
    "MonsoonHydroclimateResult",
    "SnowlineConfig",
    "SnowlineError",
    "SnowlineResult",
    "compute_monsoon_hydroclimate",
    "compute_perennial_snowline",
    "compute_snowline",
]
